version: "3.8"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - 8001:8001
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=68@)%1#wppms7af!0r@b8%0#05j*kc3r3ym5!$$fwszhl7b6b*#"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
