# Generated by Django 3.1.13 on 2021-09-23 23:54

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0002_auto_20210922_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
