# Generated by Django 3.1.13 on 2021-09-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20210923_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='albums.Location'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='albums.Tag'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='albums.Location'),
        ),
    ]
