# Generated by Django 3.1.13 on 2021-11-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20211031_1037'),
        ('albums', '0005_auto_20211010_1608'),
    ]

    operations = [
    ]
