# Generated by Django 3.1.13 on 2021-12-10 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 4, 49, 59, 555681, tzinfo=utc), verbose_name='date published'),
        ),
    ]
