# Generated by Django 3.1.13 on 2021-12-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_profile_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
